### ISSUE TITLE
How do I change the host server

### ISSUE THREAD

**Issue by Doncz19** [alecxcode/edm#1]
How do I change the host server from localhost to IP address in the EDM installation directory for Windows?

**Comment by alecxcode** [comment]
Please read the [Admin Docs](https://edmproject.github.io/manual-admin.html) to understand how to configure the program. The Admin Docs are available either online, or in your local installation.
To change the IP address to which the server binds, edit config file `edm-system.cfg` in `.edm` folder of a user home folder. You need the `ServerHost` option. Either make it empty to allow the server on all interfaces, or specify the IP address of your selected interface.
